import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { prisma } from '@/lib/prisma';
import "./globals.css";

prisma.$connect()
  .then(() => console.log("✅ Veritabanı bağlantısı kuruldu"))
  .catch((e) => console.error("❌ Veritabanı bağlantısı kurulamadı:", e))

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
